version: '3.8'

services:
  qwen-code:
#    build: .
    image: epk/qwen-code-docker:0.1.0
    hostname: qwen-code
    # Изоляция: NAT-режим без доступа извне и к локальной сети
    network_mode: bridge
    dns:
      - 8.8.8.8
      - 8.8.4.4
    environment:
      # Блокировка доступа к локальной сети через переменные окружения
      - NO_PROXY=localhost,127.0.0.1
      - no_proxy=localhost,127.0.0.1
    # Security: ограничение возможностей контейнера
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    read_only: false
    tmpfs:
      - /tmp
    # Общая папка
    volumes:
      - ./shared:/home/qwen/shared:rw
      - ./qwen-data:/home/qwen/.qwen:rw

    # копия skills
    command: >
      bash -c "
        if [ -d './shared/0-skills' ]; then
          mkdir -p /home/qwen/.qwen/skills &&
          cp -r ./shared/0-skills/* /home/qwen/.qwen/skills/ 2>/dev/null || true;
        fi;
        exec bash
       "
    # Ресурсы (опционально)
    deploy:
      replicas: 2
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 512M
    # Интерактивный режим
    stdin_open: true
    tty: true
